### ISSUE TITLE
EditorSceneHandler的WaitForCompletion有问题!

### ISSUE THREAD

**Issue by xxgamecom** [xasset/xasset#101]
```c#
public void WaitForCompletion(SceneRequest request)
        {
            var parameters = new LoadSceneParameters
                {loadSceneMode = request.withAdditive ? LoadSceneMode.Additive : LoadSceneMode.Single};
            // 这里返回的scene实际上不一定是已经完全加载的。
            // var scene =  EditorSceneManager.LoadSceneInPlayMode(request.path, parameters); 
            //  查看 scene的状态: isLoaded = false, loadingState = Loading
            EditorSceneManager.LoadSceneInPlayMode(request.path, parameters); 
            
            //  这里直接认为加载成功了
            request.SetResult(Request.Result.Success);
        }
```

所以上面会导致Simulation模式下的 Scene.Load同步接口有问题。

Unity文档里查到：
Note that this function behaves the same as [SceneManager.LoadScene](https://www.taikr.com/docs/UnityDocumentation_2019.1/ScriptReference/SceneManagement.SceneManager.LoadScene.html) meaning that the load does not happen immedately but is guarantee to complete in the next frame. This behavior also means that the Scene that is returned has its state set to Loading.

**Comment by mmdnb** [comment]
你可以在业务层借助 SceneManager.sceneLoaded 处理下一帧场景才出来的问题。
