### ISSUE TITLE
遇到一个场景加载的问题!

### ISSUE THREAD

**Issue by xxgamecom** [xasset/xasset#102]
问题：
Scene.LoadAsync加载场景后，不会立即释放掉之前场景的依赖资源。
Recycler组件不会立即释放掉场景，会导致场景的Depenedences里的bundle包不会立即被释放。
也就是说场景即使有更新了，也不会加载到最新的。
我遇到在真机出现了奔溃的情况，大致的日志为：
多条warning日志：The reference script unknown on this behaviour is missing!
最后游戏奔溃：the file 'none' is corrupted! remove it and launch unity again!

步骤：
1) 先在Samples中的CheckForUpdates场景中的“清理”按钮旁边加一个"重载"按钮，用于立即重新加载CheckForUpdates场景，代码如下：
```c#
public void Reload()
{
    Scene.LoadAsync(SamplesScene.CheckForUpdates.ToString());
}
```
2. 重新打bundle包，进CheckForUpdates，下载更新。
3.  点击重载按钮，此时CheckForUpdates还是老的。不会更新到最新的。
日志信息：
[xasset] Load SceneRequest Assets/xasset/Samples/Scenes/CheckForUpdates.unity Success.
[xasset] Unload SceneRequest Assets/xasset/Samples/Scenes/CheckForUpdates.unity.
先加载了SceneRequest，后释放了SceneRequest。dependences里还是依赖老的bundle。
调试发现:
```c#
public static Dependencies LoadAsync(ManifestAsset asset)
{
     // 这里的asset 内的 manifest字段已经是要了最新的清单json，但由于使用asset.path加载到的还是老的。
     // 我的临时做法是调整了该类的Loaded字典的key 来规避了这个问题 （key = asset.path + asset.manifest.name）
     // 可以考虑给Manifest加个hash字段，从version.hash赋值过来，然后 key = asset.path + asset.manifest.hash 
     // var key = $"{asset.path}_{asset.manifest.name}";
     // if (!Loaded.TryGetValue(key, out var value))
     if (!Loaded.TryGetValue(asset.path, out var value))
     {
           ....
     }

     value.LoadAsync();
     ....
}
```

以上只是复现问题的测试步骤，我的实际项目中，不是这么简单的在同一个场景里面用重载按钮去重新加载。
我的实际项目中热更阶段有两个场景：Startup场景，Launcher场景。
Startup场景会做一些初始化工作，然后切到Launcher场景。
Launcher场景里会进行资源更新，其中有一个判断是不是有更新了Launcher部分，如果有的话，会Reload Game，重新回到Startup场景，重新开始热更流程。
实际也碰到了先加载Launcher场景，后释放场景的情况，也就是上面3)的日志里提到的，会一直占用老的bundle包而不会释放。
这里也是导致奔溃的原因。（奔溃后再打开游戏就不会有问题，因为bundle加载正确了。）

另外：
AssestRequest也有类似的依赖问题。如果场景中依赖的资源，正好被多个人依赖，也就是refcount>1。这个时候，如果如何保持加载到最新的是个问题。有可能出现一部分是用了新的依赖，一部分用了旧的依赖的情况。因为Dependencies里的LoadAsync()使用了 asset.path 做为key进行加载。

**Comment by mmdnb** [comment]
这是个非常好的案例和解决方案，感谢反馈！

Asset 层的 Cache 默认的 key 默认是不带 version 进行缓存的，所以更新后，已经加载的资源要释放后才能加载到新的版本。

Bundle 层的 Cache 默认的 key 默认是带 version 进行缓存的，已经加载的 Bundle，加载新版本后，会先把旧的 bundle Unload false，然后再加载新的 Bundle。

所以，默认在 xasset 中，在不修改 Asset 层的 Cache 的 key 的时候，已经加载的旧的 Asset 没有释放完成前，是加载不到更新后的 Asset，而没有加载过的 Asset 不会受到影响。

下个版本会考虑新的缓存机制来优化这个 issues，同时，会给你记录 10 点声望。预计会在 16 日左右发布。

**Comment by mmdnb** [comment]
这里 专业版将支持 对更新后已经加载的资源中有变化的部分进行热重载 预计23日发布 开源版暂时不支持

**Comment by mmdnb** [comment]
已经提供了其他方案：

# 2023.1 prev-Release：增加 ReloadRequest 提供资源层的热重载机制，统一配置入口
