### ISSUE TITLE
updateinfo.json文件写入的位置是不是不对？

### ISSUE THREAD

**Issue by liqingming** [xasset/xasset#104]
以下是Builder中的方法BuildUpdateInfo

1. public static void BuildUpdateInfo(Versions versions, string hash, long size)
2. {
3.     var settings = Settings.GetDefaultSettings();
4.     var downloadURL = $"{settings.downloadURL}{Assets.Bundles}/{Settings.Platform}/";
5.     var updateInfoPath = Settings.GetCachePath(UpdateInfo.Filename);
6.     var updateInfo = Utility.LoadFromFile<UpdateInfo>(updateInfoPath);
7.     updateInfo.hash = hash;
8.     updateInfo.size = (ulong) size;
9.     updateInfo.file = versions.GetFilename();
10.     updateInfo.version = PlayerSettings.bundleVersion;
11.     updateInfo.downloadURL = downloadURL;
12.     updateInfo.playerDownloadURL = settings.playerDownloadURL;
13.     File.WriteAllText(updateInfoPath, JsonUtility.ToJson(updateInfo));
14. }
我的疑问是第5行现在拿到的是BundlesCache目录，那最终updateinfo.json也会写入到Cache目录下，但是版本相关的文件不应该写入到Bundles目录下吗？这里是否有问题？

**Comment by mmdnb** [comment]
这里是为了适配 UOS CDN，发布流程是：
1、上传 bundle + 版本信息 （都在 Bundles 里面）
2、上传更新信息 updateinfo.json （在 BundlesCache 里面）
如果 1 没完成就先发布 2，那么就会出现必然的更新异常。
了解更多，可以参考：https://uos.unity.cn/partner/xasset
