### ISSUE TITLE
Unity3d HDRP 外部加载透明材质会失效

### ISSUE THREAD

**Issue by 19920716** [xasset/xasset#105]
![2](https://github.com/xasset/xasset/assets/19903385/c2e87ccc-fb60-4ff5-a57b-e68ddebf3d90)
![1](https://github.com/xasset/xasset/assets/19903385/bcf106c7-97b4-4d4e-8891-ef877bcdb0ee)

**Comment by mmdnb** [comment]
可以自行用 Frame Debugger 对比渲染参数，看看 keywords 是否一致，如果不一致就用 SVC 采集打包加载下。

**Comment by 19920716** [comment]
不知所云，什么是SVC

**Comment by mmdnb** [comment]
google 下 unity shader 变体收集。
