### ISSUE TITLE
[xasset] Initialize Failed with error HTTP/1.1 404 Not Found(file:///C:/ProjectUnityProject/Dev/Assets/StreamingAssets/Bundles/playerassets.json).

### ISSUE THREAD

**Issue by lil-hope** [xasset/xasset#107]
[xasset] Initialize Failed with error HTTP/1.1 404 Not Found(file:///C:/ProjecUnityProject/Dev/Assets/StreamingAssets/Bundles/playerassets.json).

按教程来提示这个

**Comment by mmdnb** [comment]
你这是跑了真机模式更新，编辑器打包资源后，需要先执行build player assets
