### ISSUE TITLE
异步转同步

### ISSUE THREAD

**Issue by zhouyq041** [xasset/xasset#115]
想问下，如果已经有一个正在加载的AssetBundleRequest，这时候我想同步加载同名资源，会不会直接标记请求状态Failed然后失败呀

**Comment by mmdnb** [comment]
资产Load请求在Unity源码底层都是异步请求，异步转同步只是把异步请求block住等待完成后再继续，实际同步加载API的底层实现也是如此。

**Comment by zhouyq041** [comment]
哦哦是这样~看代码好像那个同步请求直接会失败？我是需要在业务逻辑层用协程之类等待同名的异步加载结束吗？
