### ISSUE TITLE
Asset.Load依赖加载不全。加载时，仅加载了资源本身的Bundle与直接依赖的Bundle，并没有去加载深层次依赖的Bundle。

### ISSUE THREAD

**Issue by kkqihan** [xasset/xasset#116]
资源：
    3个Prefab：A.prefab、B.prefab、C.prefab
    3个Prefacb分别打成独立的Bundle

引用关系:
    在每个预制上挂载引用脚本，形成引用关系。

    public class RefObj : MonoBehaviour
    {
        public GameObject obj;
    }

    A.prefab引用了B.prefab、B.prefab引用了C.prefab

问题复现：
    加载A.prefab，然后分别实例化B.prefab、C.prefab。会发现B.prefab引用的C.prefab丢失了。

    private IEnumerator Start()
    {
        var initializeAsync = Assets.InitializeAsync();
        yield return initializeAsync;

        GameObject preA = Asset.Load("Assets/xasset/Samples/TestDep/A/A.prefab", typeof(GameObject)).asset as GameObject;
        GameObject objA = Instantiate(preA);

        GameObject preB = objA.GetComponent<RefObj>().obj;
        GameObject objB = Instantiate(preB);

        GameObject preC = objB.GetComponent<RefObj>().obj;
        GameObject objC = Instantiate(preC);
    }

**Comment by mmdnb** [comment]
打包代码版本不对，没有收集所有依赖，下个版本修复。

**Comment by mmdnb** [comment]
已经修复，更新反馈！预计最快2个月内会发布全新版本，感兴趣可以留意仓库更新。
