### ISSUE TITLE
关于Plugins.XAsset.Assets.Unload接口的用法

### ISSUE THREAD

**Issue by songtm** [xasset/xasset#23]
感觉跟直接 asset.Release 的作用是一样的; 而且下图框中的代码应该也不会执行到, 因为_unusedAssets在 Update 函数中已经清空了, 也不会有其它地方往里添加元素.
![QQ20190718-161324](https://user-images.githubusercontent.com/8175056/61440921-36f8fb00-a977-11e9-9783-02aae4e1f441.png)

**Comment by fengjiyuan** [comment]
其实这个接口可以不需要用，只是有了load然后提供一个可以配对的unload
