### ISSUE TITLE
关于 sprite atlas late binding AB 包卸载时机的问题

### ISSUE THREAD

**Issue by songtm** [xasset/xasset#26]
作者你好!  
项目UGUI使用了新版的 sprite atlas, 一个 UI 模块对应了一个 sprite atlas, 用一个 全局的SpriteAtlasLoader.cs负责 atlas 的加载;
根据[官方文档](https://docs.unity3d.com/ScriptReference/U2D.SpriteAtlasManager-atlasRequested.html)的介绍, 要实现 late binding,得使用SpriteAtlasManager.atlasRequested; 但是并不知道这个 sprite atlas Asset 什么时候使用完毕, 那应该什么时候调用 Asset.Release呢?
![11](https://user-images.githubusercontent.com/8175056/61621342-5eb4cf80-aca5-11e9-84cb-e6f22af2d41b.png)

**Comment by fengjiyuan** [comment]
这个是对象生命周期管理的问题。你在加载后，需要自己把握这个图集的生命周期在什么时候结束，比如说界面关闭，比如说状态切换，如果觉得麻烦的话可以利用Require机制处理这个问题：例如，每次加载后把设置一个关注对象，在对象销毁时自动回收。
