### ISSUE TITLE
WebGL无法加载

### ISSUE THREAD

**Issue by tragicy** [xasset/xasset#31]
NullReferenceException: A null value was found where an object instance was required.
UnityLoader.js:4   at Plugins.XAsset.Bundles.Load (System.String assetBundleName, Boolean isLoadingAssetBundleManifest, Boolean asyncMode) [0x00000] in <filename unknown>:0 
UnityLoader.js:4   at Plugins.XAsset.Bundles.Initialize (System.String path, System.String platform, System.Action onSuccess, System.Action`1 onError) [0x00000] in <filename unknown>:0 
UnityLoader.js:4   at Plugins.XAsset.Assets.Initialize (System.Action onSuccess, System.Action`1 onError) [0x00000] in <filename unknown>:0 
UnityLoader.js:4   at AssetsInit.Start () [0x00000] in <filename unknown>:0 
UnityLoader.js:4  
UnityLoader.js:4 (Filename: currently not available on il2cpp Line: -1)

**Comment by fengjiyuan** [comment]
麻烦提供下引擎版本，2019.1 看不了你这种详细堆栈

**Comment by songtm** [comment]
测试发现webgl 下面ugui相关的GameObject会出现script missing的现象(stripping关闭的情况下); 可能是unity本身的bug?; 非ui相关的暂未发现异常
![DD6A736FD24CEB9E97C0D91AF2B68923](https://user-images.githubusercontent.com/8175056/62406090-ace89d80-b5d8-11e9-874f-2338a434fdbf.jpg)

**Comment by songtm** [comment]
还有个注意的点是 webGL下只能调用异步接口
