### ISSUE TITLE
Download分段下载问题

### ISSUE THREAD

**Issue by y85171642** [xasset/xasset#37]
问题代码：
https://github.com/xasset/xasset/blob/7f9b9e59a7c6eead8f82393f38b37e2f7e430463/Assets/Plugins/XAsset/Download.cs#L127

应改为：
    `request.SetRequestHeader("Range", "bytes=" + len + "-" + (maxlen - 1));`

或者干脆改为：
   `request.SetRequestHeader("Range", "bytes=" + len + "-");`

详细参考：
[https://www.cnblogs.com/OIMM/p/9144798.html](https://www.cnblogs.com/OIMM/p/9144798.html)

多说两句：
我觉得这个maxlen的真正意义是为了分段下载，避免一次下载内容长度过长，导致内存占用过高。希望作者可以重新梳理下逻辑。

**Comment by fengjiyuan** [comment]
see：Merge pull request #38 from y85171642/master

**Comment by fengjiyuan** [comment]
Merge pull request #38 from y85171642/master
