### ISSUE TITLE
WebGL平台加载报错

### ISSUE THREAD

**Issue by wangxuanrui** [xasset/xasset#39]
![20191120122129489](https://user-images.githubusercontent.com/23449845/69208927-5192e900-0b90-11ea-8e39-cbb17059c9f2.jpg)

请问是什么问题呢？

**Comment by wangxuanrui** [comment]
已解决：去掉勾选 “Strip Engine Code ” 即可，又发现另外一个BUG，WebGL 平台， 在获取DownloadRUL 地址中始终是 http://127.0.0.1 的地址

**Comment by fengjiyuan** [comment]
downloadURL 可以自己配置，在settings.asset 文件
