### ISSUE TITLE
提供LoadAssetWithSubAssets的支持

### ISSUE THREAD

**Issue by huahanyan** [xasset/xasset#40]
作者您好，我在使用过程中需要加载一个用multiple模式切分的sprite，得到一个包含切分好的sprite的array。但是这个功能框架里好像没有提供。xasset好像只用到了LoadAsset和LoadAssetAsync这两个函数，没有提供对LoadAssetWithSubAssets的支持，如果要加上这个功能的话应该放在哪里呢？

**Comment by fengjiyuan** [comment]
你有需要可以自己仿造 BundleAsset（Async）针对 LoadAssetWithSubAssets 写一个新的 Asset 哈
