### ISSUE TITLE
BUG：配置丢失

### ISSUE THREAD

**Issue by yomunsam** [xasset/xasset#48]
现象：当在一处新的位置clone下工程后，配置信息（Rule和Manifest）丢失

复现方法：

关掉Unity Editor ，删掉已有工程的`Library`目录，然后重新打开编辑器，观察到配置信息丢失：
![image](https://user-images.githubusercontent.com/24813704/87751629-0caf7700-c831-11ea-81a2-d072cdeaaa6e.png)

------

之前遇到类似的坑，猜测原因如下：
![image](https://user-images.githubusercontent.com/24813704/87751723-4a140480-c831-11ea-9ca1-23043f65211e.png)

在没有Library时，Unity会先构建代码，这时候如果我们有在项目刚打开时候做“判断资源在不在，如果不在就创建”的操作时，由于Unity Editor还没有读取到配置文件， `AssetDatabase`会始终得不到资源。
此时执行创建操作，会覆盖原有资源

**Comment by mmdnb** [comment]
问题已经修复
