### ISSUE TITLE
Mac系统跑Demo跑不通，是因为分析平台的时候代码写错了

### ISSUE THREAD

**Issue by GEMLittleY** [xasset/xasset#58]
Updater.cs

case RuntimePlatform.OSXEditor:
                case RuntimePlatform.OSXPlayer:
                    return "iOS"; // OSX

改为

case RuntimePlatform.OSXEditor:
                case RuntimePlatform.OSXPlayer:
                    return "OSX"; // OSX

**Comment by mmdnb** [comment]
7.0 体验版发布了。全新的下载器，可以更新试试
