### ISSUE TITLE
关于assetbundle name设置的疑惑

### ISSUE THREAD

**Issue by LouisSong** [xasset/xasset#69]
示例项目中有四个assetbundle name，分别是sprites、prefabs、scenes、textures，编译ab后，其中sprites对应的资源是Logo.png和Grids.png，但是选中这两个图片，右下角assetbundle name显示为none，点击右下角的remove unused names,也没有移除上面4个abname，请问这4个abname对应的资源，是在哪里设置的？

**Comment by XINCGer** [comment]
是在文件夹上设置的assetbundle name。
![QQ拼音截图20210823112046](https://user-images.githubusercontent.com/10908565/130385660-3955dcad-5b37-4544-9ad7-7e8d2af6975b.png)

**Comment by LouisSong** [comment]
原来如此，谢谢及时回复！
