### ISSUE TITLE
希望可以手动控制版本生效

### ISSUE THREAD

**Issue by getwisdom** [xasset/xasset#73]
现在versions.json 的生效在DownloadAsync()中 如果在bundles下载前使用到bundle中资源将会自动从cdn中下载 
需要提供接口 可以在bundles下载完成后再生效新版资源

**Comment by mmdnb** [comment]
预计4月25日前会发布新版本修复此问题

**Comment by mmdnb** [comment]
2022.1p3 版本已经处理
