### ISSUE TITLE
Android平台热更问题，Download使用WebRequest异常

### ISSUE THREAD

**Issue by fadedFantastic** [xasset/xasset#75]
打Android包在手机上测试，发现热更总是失败，打debug包发现，在创建WebRequest直接就异常了，捕捉到的异常信息也为null，很是奇怪
```
private WebRequest GetHttpWebRequest()
{
      var request = (HttpWebRequest) WebRequest.Create(info.url)
}
```

**Comment by mmdnb** [comment]
> 打Android包在手机上测试，发现热更总是失败，打debug包发现，在创建WebRequest直接就异常了，捕捉到的异常信息也为null，很是奇怪
> 
> ```
> private WebRequest GetHttpWebRequest()
> {
>       var request = (HttpWebRequest) WebRequest.Create(info.url)
> }
> ```

可以打印下 url，重点关注下 Downloader.downloadURL，Downloader 组件在 Awake 的时候会读取 downloadURL。

**Comment by mmdnb** [comment]
2022.2 版本已经提交，提供了基于UnityWebRequest实现的全新的下载器，可以更新体验下。
