### ISSUE TITLE
网络较差时，有增量更新时，version.json的更新还没完成，立刻点击下载调用Versions.CheckUpdateAsync()有报错

### ISSUE THREAD

**Issue by MrJLY** [xasset/xasset#76]
在网络较差情况下打开游戏会调用一次Versions.CheckUpdateAsync()进行版本文件更新，这时候如果进入了游戏，version.json还没更新完，点击下载某个东西又会检查更新调用Versions.CheckUpdateAsync()，两次调用会造成version.json文件的读写冲突：
![Image](https://user-images.githubusercontent.com/35212232/187874301-c69e9eff-f2e2-491f-88bb-85e9f3fe4977.png)

**Comment by MrJLY** [comment]
同理，清单文件如果网速较差没更新完，也可能出现读写冲突：
![image](https://user-images.githubusercontent.com/35212232/187874779-7d998a74-e9da-49c2-bad9-8e51a5764213.png)

**Comment by mmdnb** [comment]
> 在网络较差情况下打开游戏会调用一次Versions.CheckUpdateAsync()进行版本文件更新，这时候如果进入了游戏，version.json还没更新完，点击下载某个东西又会检查更新调用Versions.CheckUpdateAsync()，两次调用会造成version.json文件的读写冲突： ![Image](https://user-images.githubusercontent.com/35212232/187874301-c69e9eff-f2e2-491f-88bb-85e9f3fe4977.png)

CheckUpdateAsync 需要阻塞调用。

**Comment by mmdnb** [comment]
和网络状态没啥关系，Versions.CheckUpdateAsync 需要阻塞调用，游戏启动的生命周期中，不能出现一个调用还没完成另外一个调用就启动的情况。 @MrJLY 可以确认下看是不是这个情况？

**Comment by MrJLY** [comment]
是的，谢谢~
