### ISSUE TITLE
下载失败之后，自动retry有问题

### ISSUE THREAD

**Issue by MrJLY** [xasset/xasset#78]
偶现问题，有时候下载会失败，但是开启了自动retry，发现retry之后会导致bundle加载失败
![image](https://user-images.githubusercontent.com/35212232/198969694-023a8123-46d6-4626-a3cd-44ade514bc9b.png)
如果一次性下载成功，没有出现retry则可以正常加载bundle

**Comment by mmdnb** [comment]
感谢反馈，这个是之前考虑不周，这种情况下应该弹窗提示用户而不是自动 Retry，Retry 没有放在 DownloadBundle 内部而是放在 Downloader 里面，导致下载失败的时候一些状态不同步。预计下个版本会优化这个问题，应该在这周三晚上9:30前会同步到仓库。
