### ISSUE TITLE
加载资源报错

### ISSUE THREAD

**Issue by RouderSky** [xasset/xasset#80]
![image](https://user-images.githubusercontent.com/18010177/203121453-c89ea845-a3d8-474e-b380-a0f7268b5b34.png)
![image](https://user-images.githubusercontent.com/18010177/203122527-561a9e41-14e6-453b-9c1e-bdf0e9a353ae.png)
![image](https://user-images.githubusercontent.com/18010177/203121635-ec383f30-86de-473b-b562-abd27a0e2554.png)
![image](https://user-images.githubusercontent.com/18010177/203121109-33113980-d170-4b45-bef1-8e70983f6c02.png)
![image](https://user-images.githubusercontent.com/18010177/203121192-b2f8a119-4c64-4794-936c-48bb1b276953.png)

**Comment by mmdnb** [comment]
可以勾选SimulationMode运行，或者打包后把资源Copy到StreamingAssets下面运行，有个xasset>BuildPlayerAssets的菜单可以快速copy。

**Comment by RouderSky** [comment]
还想请教下
如果不勾选Downloader中的Simulation Mode，是不是就可以网络下载效果
我试了一下，也是报下面的错
![image](https://user-images.githubusercontent.com/18010177/203603380-dad7e680-5dd2-4f74-8d65-afda74d953e9.png)

**Comment by RouderSky** [comment]
貌似好像是因为开源版不支持网络下载功能

**Comment by mmdnb** [comment]
2022.2.3 发布了，支持离线模式，支持简易分包，支持直接加载服务器的资源，了解更多可以查看 Readme。
