### ISSUE TITLE
如果我现在使用2022.02.03开源版，之后升级到付费专业版，升级过程麻烦吗

### ISSUE THREAD

**Issue by RouderSky** [xasset/xasset#81]
使用开源版的时候我不会对xasset代码框架做任何调整，单纯使用

**Comment by mmdnb** [comment]
开源版的API和专业版几乎可以无缝对接。专业版会增加一些可以节省更多团队时间的特性，例如，加密、二次打包网络IO优化机制、局部更新、完整分包含google play适配，依赖引用关系分析检索工具，加载统计工具，RawAsset资源管理、技术对接群等支持。

**Comment by RouderSky** [comment]
感谢！
