### ISSUE TITLE
严重Bug：用了xasset.Scene.Load之后，无论场景在不在Scene in Build列表中，该场景中部分纹理都会丢失

### ISSUE THREAD

**Issue by RouderSky** [xasset/xasset#85]
用回 UnityEngine.SceneManagement.SceneManager.LoadScene 就没问题

**Comment by RouderSky** [comment]
补充一下，丢失纹理只被场景中的sphere引用，该sphere不是prefab
加载模型prefab没有问题

**Comment by mmdnb** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/25072236/206900762-a05a874e-d301-48ea-89ba-6e551af3215c.png">

**Comment by mmdnb** [comment]
@RouderSky 可以上传下你的测试素材。

**Comment by RouderSky** [comment]
是打包后才会丢，编辑器下正常

**Comment by RouderSky** [comment]
![image](https://user-images.githubusercontent.com/18010177/207372126-cc20d5f7-6ce1-4510-bacc-b5c74b5fc634.png)
图还在，效果没了

**Comment by RouderSky** [comment]
不开Simulation效果是下面这样的
![image](https://user-images.githubusercontent.com/18010177/207372821-e730ad89-ce09-4d83-9a6e-1f44b4bcc861.png)

**Comment by RouderSky** [comment]
编辑器下开Simulation还是好的，打包后就不对了

**Comment by RouderSky** [comment]
编辑器下开simulation
![image](https://user-images.githubusercontent.com/18010177/207374909-8db44c04-faa5-4342-96f5-d9bf3e640d7d.png)

**Comment by RouderSky** [comment]
打包后
![image](https://user-images.githubusercontent.com/18010177/207375030-34c43fef-3c5e-4304-b9bf-346851968bdb.png)

**Comment by mmdnb** [comment]
> 

你可以用 FrameDebugger 调试下，看编辑器 SimulationMode 下这个材质渲染的属性和打包后，从 Bundle 里面加载出来的材质渲染的属性的差异。另外，打包后加载，也可以把 Inspector 里面的内容截图下。

**Comment by KDliyulong** [comment]
我也遇到类似问题了，打包安卓之后部分材质丢失，请问你这个解决了吗，怎么解决的

**Comment by xxgamecom** [comment]
我也遇到了类似的问题，Android下，首次打开一个prefab没问题。关闭后再打开，就出现了粉色的。shader丢了。用framedebug看了，发现有个shader报 Hidden/InternalErrorShader。怀疑是不是关闭窗口的时候，也把Shader的bundle包也给卸载了。

**Comment by xxgamecom** [comment]
我大概定位到问题了。我打bundle后发现居然依赖了多个shaders_hash.bundle文件。但在清单文件中它们的name都是shaders.bundle，只是hash不一样。

xasset中收集资源的时会把 .shader 和 变体文件 打包到单个 shaders.bundle文件中。但由于我有多个build，这就导致了可能出现这几个build里所依赖的shaders可能会不同。

我不知道这是不是导致shader丢失的问题所在。

**Comment by mmdnb** [comment]
参考 #97
