### ISSUE TITLE
RuntimeAssetHandler这边是不是写的有问题？

### ISSUE THREAD

**Issue by lemon0721** [xasset/xasset#87]
RuntimeAssetHandler 的 Dispose 释放函数是不是应该加上 _loadAssetAsync = null？ 因为如果 Request 重用 再次调用 WaitForCompletion  时候判断不通过导致不会进入 LoadAssetAsync 函数
(https://user-images.githubusercontent.com/41471675/207810392-ce80149b-9518-448b-a828-985400325f89.png)

**Comment by mmdnb** [comment]
有这个意识非常好，handler不是复用的所以没事

**Comment by mmdnb** [comment]
非常好的议题，最近在和新冠做对抗，晚些会优化这个
