### ISSUE TITLE
新版本Demo怎么去加载cdn资源阿

### ISSUE THREAD

**Issue by liuyingbor** [xasset/xasset#90]
![20230111-000516](https://user-images.githubusercontent.com/93653683/211602066-8d5984e6-13c3-4cb6-9ad9-1f5c87ec5e20.jpeg)

**Comment by mmdnb** [comment]
更新到最新主干代码后：
1. 在 Settings 中关闭 Offline Mode 和 Simulation Download
2. 把 Bundles 添加到 hfs 中
3. 在 Settings 中把  PlayerAssetsSplitMode 改成 ExcludeAllAssets
4. 在 Unity 编辑器中选择 xasset>Build Player Assets 
5. 启动 Unity 播放器。

**Comment by Wang1075457479** [comment]
请问加载CDN资源时，DownloadURl需要在entry_by_path/content/?path=  后边加上具体的bundle地址吗？
