### ISSUE TITLE
关于增量更新

### ISSUE THREAD

**Issue by dabaize** [xasset/xasset#93]
作者你好，
咨询一个问题
我有一个组TextureGroup，当我需要增量其中Texture 1时，是否需要增量整个TextureGroup完成更新呢？

Xasset是否支持类似Addressables的Check for Content Update Restrictions（检查内容更新限制）功能，只对修改的文件做增量更新？

**Comment by mmdnb** [comment]
xasset的更新本身就是增量更新，更新粒度是以bundle为单位，1个bundle里面只要修改了1个资源，整个bundle就会更新。检查bundle更新的接口是，Assets.GetDownloadSizeAsync，可以输入，资源路径，目录等参数。
