### ISSUE TITLE
关于versions_vX.json文件的问题

### ISSUE THREAD

**Issue by xxgamecom** [xasset/xasset#95]
如果有比较多的build的话，会出现versions_v1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.json这种奇怪的文件，建议调整下版本号的策略。因为我的项目中有几十个build，也不知道是什么原因，直接导致在用jenkins打包时，unity直接到后面就shutdown了～
我目前的做法是：
1）动态计算bundle data目录下的versions_vX.json的版本号；
2）bundle data不存在version_vX.json时使用versions_v1.json；
3）存在时，如果versions文件内的data部分和bundle cache中的一致则不更新版本文件依旧使用该版本；
4）如果不一致，则取最大版本号版本信息文件versions_vX.json的X+1作为新的版本号。
这样就不会出现这种奇怪的文件。

**Comment by mmdnb** [comment]
项目里面不建议搞很多 Build 配置，Build 配置的使用是有限制的，可以参考：https://xasset.cc/docs/2022.1/nocentral
versions_vX.json X 取决于 Build 的数量，一般来说，常规项目可以把 配置 和 资源 分拆到不同的 Build 配置，要划分更多的 Build 配置，需要对依赖打包规则足够了解。
