### ISSUE TITLE
关于官方文档里提到的Assets.GetDownloadSizeAsync(versions, assetContainer.GetAssets())接口

### ISSUE THREAD

**Issue by xxgamecom** [xasset/xasset#96]
在例子文档中看到了这个接口：
// 查询 assetContainer.GetAssets() 返回的资源是否需要下载更新。
var getDownloadSizeAsync = Assets.GetDownloadSizeAsync(versions, assetContainer.GetAssets());
这个接口在代码中没有找到，请问这个是付费版的功能吗？assetContainer是主要用来做什么的？

之前的版本里有个根据清单获取更新大小的接口，新版本里貌似被取消了。

比分说我有100个关卡，每次进关卡之前都要看下资源是不是有更新。我目前是做了100个Build，类似于之前的清单文件。
每次进关卡之前，使用GetDownloadSizeAsync检查下这个build是不是有更新。
        public static GetDownloadSizeRequest GetDownloadSizeAsync(string buildName)
        {
            var versions = ScriptableObject.CreateInstance\<Versions\>();
            versions.data = Versions.data.Where(version => buildName.Equals(version.name)).ToList();
            return GetDownloadSizeAsync(versions);
        }

**Comment by xxgamecom** [comment]
如果按照开源版的只有Assets.GetDownloadSizeAsync(versions)接口，要如何能实现按需下载？

**Comment by mmdnb** [comment]
是专业版的功能。
