### ISSUE TITLE
多个build配置，并选择将shaders打到单个文件中，清单中会出现依赖多个不同shaders.bundle的情况。

### ISSUE THREAD

**Issue by xxgamecom** [xasset/xasset#97]
这可能是 #85 问题中我遇到材质里shader丢失的原因。
我用assetstudio看了bundle 的内容。其中有个shaders_xxx.bundle里面有两个shader在另外一个shaders_xxx.bundle里存在。也正好是导致 Hidden/InternalErrorShader 错误的 shader。

我的项目中我能保证各个build之间是不会有多重依赖存在的情况。但是shader是一个问题，是共用的。多个build会出现这个问题。

我这里清单bundles数组中出现的情况：

build1
    {
      "name": "shaders.bundle",
      "hash": "8c703d9eb731e4f285494e08409edac7",
      "size": 20215,
      "deps": []
    },

build2
    {
      "name": "shaders.bundle",
      "hash": "4b2217ac3269e0b29eb734f482eb7888",
      "size": 32980,
      "deps": []
    }

build3
    {
      "name": "shaders.bundle",
      "hash": "37a421c67f0acb39c296d5f755e722d2",
      "size": 254341,
      "deps": []
    }

**Comment by mmdnb** [comment]
同一个资源不能出现在不同的build中，有这个限制。
